name: Automate Release

on:
  release:
    types: [published]

jobs:
  merge-main-into-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Merge main into deploy
        run: |
          git checkout deploy
          git merge main --no-ff -m "Merge main into deploy following release ${{ github.event.release.tag_name }}"
          git push origin deploy --follow-tags
